---
- name: Start AWX Job
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch a Job with extra_vars without waiting
      awx.awx.job_launch:
        job_template: "{{ job_name }}"
        extra_vars: "{{ job_extra_vars }}"
